/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mess9.testitaffectedidplugin.testit.dto;

import com.google.gson.annotations.SerializedName;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AutoTestStep
 */
@Getter
@SuppressWarnings("unused")
public class AutoTestStep {

	public static final String SERIALIZED_NAME_TITLE = "title";
	public static final String SERIALIZED_NAME_DESCRIPTION = "description";
	public static final String SERIALIZED_NAME_STEPS = "steps";
	/**
	 * -- GETTER --
	 * Step name.
	 */
	@SerializedName(SERIALIZED_NAME_TITLE)
	private String title;
	/**
	 * -- GETTER --
	 * Detailed step description. It appears when the step is unfolded.
	 */
	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;
	/**
	 * -- GETTER --
	 * Includes a nested step inside another step. The maximum nesting level is 15.
	 */
	@SerializedName(SERIALIZED_NAME_STEPS)
	private List<AutoTestStep> steps;

	public AutoTestStep() {
	}

	public AutoTestStep title(String title) {

		this.title = title;
		return this;
	}


	public void setTitle(String title) {
		this.title = title;
	}


	public AutoTestStep description(String description) {

		this.description = description;
		return this;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public AutoTestStep steps(List<AutoTestStep> steps) {

		this.steps = steps;
		return this;
	}

	public AutoTestStep addStepsItem(AutoTestStep stepsItem) {
		if (this.steps == null) {
			this.steps = new ArrayList<>();
		}
		this.steps.add(stepsItem);
		return this;
	}


	public void setSteps(List<AutoTestStep> steps) {
		this.steps = steps;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AutoTestStep autoTestStep = (AutoTestStep) o;
		return Objects.equals(this.title, autoTestStep.title) &&
				Objects.equals(this.description, autoTestStep.description) &&
				Objects.equals(this.steps, autoTestStep.steps);
	}


	@Override
	public int hashCode() {
		return Objects.hash(title, description, steps);
	}


	@Override
	public String toString() {
		return "class AutoTestStep {\n" +
				"    title: " + toIndentedString(title) + "\n" +
				"    description: " + toIndentedString(description) + "\n" +
				"    steps: " + toIndentedString(steps) + "\n" +
				"}";
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}


}

