/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mess9.testitaffectedidplugin.testit.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


@SuppressWarnings("unused")
public class Label {

	public static final String SERIALIZED_NAME_NAME = "name";
	public static final String SERIALIZED_NAME_GLOBAL_ID = "globalId";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	@SerializedName(SERIALIZED_NAME_GLOBAL_ID)
	private Long globalId;

	public Label() {
	}

	public Label name(String name) {

		this.name = name;
		return this;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Label globalId(Long globalId) {

		this.globalId = globalId;
		return this;
	}


	public void setGlobalId(Long globalId) {
		this.globalId = globalId;
	}


	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Label label = (Label) o;
		return Objects.equals(this.name, label.name) &&
				Objects.equals(this.globalId, label.globalId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, globalId);
	}

	@Override
	public String toString() {
		return "class Label {\n" +
				"    name: " + toIndentedString(name) + "\n" +
				"    globalId: " + toIndentedString(globalId) + "\n" +
				"}";
	}

	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public String getName() {
		return name;
	}

	public Long getGlobalId() {
		return globalId;
	}
}

