/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.mess9.testitaffectedidplugin.testit.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
import java.util.UUID;

/**
 * Link
 */
@SuppressWarnings("unused")
public class Link {

	public static final String SERIALIZED_NAME_ID = "id";
	public static final String SERIALIZED_NAME_TITLE = "title";
	public static final String SERIALIZED_NAME_URL = "url";
	public static final String SERIALIZED_NAME_DESCRIPTION = "description";
	public static final String SERIALIZED_NAME_TYPE = "type";
	public static final String SERIALIZED_NAME_HAS_INFO = "hasInfo";
	@SerializedName(SERIALIZED_NAME_ID)
	private UUID id;

	@SerializedName(SERIALIZED_NAME_TITLE)
	private String title;

	@SerializedName(SERIALIZED_NAME_URL)
	private String url;

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;

	@SerializedName(SERIALIZED_NAME_TYPE)
	private LinkType type;

	@SerializedName(SERIALIZED_NAME_HAS_INFO)
	private Boolean hasInfo;

	public Link() {
	}

	private static <T> boolean equalsNullable(T a, T b) {
		return a == b || (a != null && b != null && Objects.deepEquals(a, b));
	}

	public Link id(UUID id) {

		this.id = id;
		return this;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public Link title(String title) {

		this.title = title;
		return this;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Link url(String url) {

		this.url = url;
		return this;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Link description(String description) {

		this.description = description;
		return this;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Link type(LinkType type) {

		this.type = type;
		return this;
	}

	public void setType(LinkType type) {
		this.type = type;
	}

	public Link hasInfo(Boolean hasInfo) {

		this.hasInfo = hasInfo;
		return this;
	}

	public void setHasInfo(Boolean hasInfo) {
		this.hasInfo = hasInfo;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Link link = (Link) o;
		return Objects.equals(this.id, link.id) &&
				Objects.equals(this.title, link.title) &&
				Objects.equals(this.url, link.url) &&
				Objects.equals(this.description, link.description) &&
				Objects.equals(this.type, link.type) &&
				Objects.equals(this.hasInfo, link.hasInfo);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, title, url, description, type, hasInfo);
	}

	@Override
	public String toString() {
		return "class Link {\n" +
				"    id: " + toIndentedString(id) + "\n" +
				"    title: " + toIndentedString(title) + "\n" +
				"    url: " + toIndentedString(url) + "\n" +
				"    description: " + toIndentedString(description) + "\n" +
				"    type: " + toIndentedString(type) + "\n" +
				"    hasInfo: " + toIndentedString(hasInfo) + "\n" +
				"}";
	}

	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public UUID getId() {
		return id;
	}

	public String getTitle() {
		return title;
	}

	public String getUrl() {
		return url;
	}

	public String getDescription() {
		return description;
	}

	public LinkType getType() {
		return type;
	}

	public Boolean getHasInfo() {
		return hasInfo;
	}
}

